FROM alpine:3.23 AS ca-certs

RUN apk --no-cache add ca-certificates

FROM scratch

ARG TARGETOS
ARG TARGETARCH

COPY ${TARGETOS}/${TARGETARCH}/tink-agent /tink-agent
COPY --from=ca-certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT [ "/tink-agent" ]
