apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.type }}
metadata:
  name: {{ .Values.rbac.name }}-role
  {{- if eq .Values.rbac.type "Role"  }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "delete", "get", "list", "patch", "update"]
  - apiGroups: ["tinkerbell.org"]
    resources: ["hardware", "hardware/status"]
    verbs: ["create", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["tinkerbell.org"]
    resources: ["templates", "templates/status"]
    verbs: ["get", "list", "patch", "update", "watch"]
  - apiGroups: ["tinkerbell.org"]
    resources: ["workflows", "workflows/status"]
    verbs: ["create", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["workflow.tinkerbell.org"]
    resources: ["rulesets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["bmc.tinkerbell.org"]
    resources: ["jobs", "jobs/status", "tasks", "tasks/status"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch", "deletecollection"]
  - apiGroups: ["bmc.tinkerbell.org"]
    resources: ["machines", "machines/status"]
    verbs: ["get", "list", "patch", "update", "watch"]
  - apiGroups: ["bmc.tinkerbell.org"]
    resources: ["jobs/finalizers", "machines/finalizers", "tasks/finalizers"]
    verbs: ["update"]