{{- if and .Values.optional.hookos.enabled (empty .Values.optional.hookos.persistence.existingClaim ) }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.optional.hookos.persistence.localPersistentVolume.storageClassName }}
  namespace: {{ .Release.Namespace | quote }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.optional.hookos.persistence.localPersistentVolume.name }}
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.optional.hookos.persistence.localPersistentVolume.size }}
  accessModes:
  {{- range .Values.optional.hookos.persistence.localPersistentVolume.accessModes }}
  - {{ . | quote }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.optional.hookos.persistence.localPersistentVolume.storageClassName }}
  local:
    path: {{ .Values.optional.hookos.persistence.localPersistentVolume.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: non-existent-label # this label with DoesNotExist should match all nodes
          operator: DoesNotExist
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hook-artifacts
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- with .Values.optional.hookos.persistence.localPersistentVolume.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  {{- range .Values.optional.hookos.persistence.localPersistentVolume.accessModes }}
  - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.optional.hookos.persistence.localPersistentVolume.size | quote }}
  storageClassName: {{ .Values.optional.hookos.persistence.localPersistentVolume.storageClassName }}
{{- end }}
