// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: get_action_request.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActionRequest
type ActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the Agent that is requesting the action
	AgentId *string `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	// Attributes of the Agent, this enables more sophisticated server-side Workflow selection and creation capabilities
	AgentAttributes *AgentAttributes `protobuf:"bytes,2,opt,name=agent_attributes,json=agentAttributes" json:"agent_attributes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_get_action_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{0}
}

func (x *ActionRequest) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

func (x *ActionRequest) GetAgentAttributes() *AgentAttributes {
	if x != nil {
		return x.AgentAttributes
	}
	return nil
}

type AgentAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *CPU                   `protobuf:"bytes,1,opt,name=cpu" json:"cpu,omitempty"`
	Memory        *Memory                `protobuf:"bytes,2,opt,name=memory" json:"memory,omitempty"`
	Block         []*Block               `protobuf:"bytes,3,rep,name=block" json:"block,omitempty"`
	Network       []*Network             `protobuf:"bytes,4,rep,name=network" json:"network,omitempty"`
	Pci           []*PCI                 `protobuf:"bytes,5,rep,name=pci" json:"pci,omitempty"`
	Gpu           []*GPU                 `protobuf:"bytes,6,rep,name=gpu" json:"gpu,omitempty"`
	Chassis       *Chassis               `protobuf:"bytes,7,opt,name=chassis" json:"chassis,omitempty"`
	Bios          *BIOS                  `protobuf:"bytes,8,opt,name=bios" json:"bios,omitempty"`
	Baseboard     *Baseboard             `protobuf:"bytes,9,opt,name=baseboard" json:"baseboard,omitempty"`
	Product       *Product               `protobuf:"bytes,10,opt,name=product" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAttributes) Reset() {
	*x = AgentAttributes{}
	mi := &file_get_action_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAttributes) ProtoMessage() {}

func (x *AgentAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAttributes.ProtoReflect.Descriptor instead.
func (*AgentAttributes) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{1}
}

func (x *AgentAttributes) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *AgentAttributes) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *AgentAttributes) GetBlock() []*Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *AgentAttributes) GetNetwork() []*Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *AgentAttributes) GetPci() []*PCI {
	if x != nil {
		return x.Pci
	}
	return nil
}

func (x *AgentAttributes) GetGpu() []*GPU {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *AgentAttributes) GetChassis() *Chassis {
	if x != nil {
		return x.Chassis
	}
	return nil
}

func (x *AgentAttributes) GetBios() *BIOS {
	if x != nil {
		return x.Bios
	}
	return nil
}

func (x *AgentAttributes) GetBaseboard() *Baseboard {
	if x != nil {
		return x.Baseboard
	}
	return nil
}

func (x *AgentAttributes) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type CPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCores    *uint32                `protobuf:"varint,1,opt,name=total_cores,json=totalCores" json:"total_cores,omitempty"`
	TotalThreads  *uint32                `protobuf:"varint,2,opt,name=total_threads,json=totalThreads" json:"total_threads,omitempty"`
	Processors    []*Processor           `protobuf:"bytes,3,rep,name=processors" json:"processors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPU) Reset() {
	*x = CPU{}
	mi := &file_get_action_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{2}
}

func (x *CPU) GetTotalCores() uint32 {
	if x != nil && x.TotalCores != nil {
		return *x.TotalCores
	}
	return 0
}

func (x *CPU) GetTotalThreads() uint32 {
	if x != nil && x.TotalThreads != nil {
		return *x.TotalThreads
	}
	return 0
}

func (x *CPU) GetProcessors() []*Processor {
	if x != nil {
		return x.Processors
	}
	return nil
}

type Processor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Cores         *uint32                `protobuf:"varint,2,opt,name=cores" json:"cores,omitempty"`
	Threads       *uint32                `protobuf:"varint,3,opt,name=threads" json:"threads,omitempty"`
	Vendor        *string                `protobuf:"bytes,4,opt,name=vendor" json:"vendor,omitempty"`
	Model         *string                `protobuf:"bytes,5,opt,name=model" json:"model,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Processor) Reset() {
	*x = Processor{}
	mi := &file_get_action_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Processor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Processor) ProtoMessage() {}

func (x *Processor) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Processor.ProtoReflect.Descriptor instead.
func (*Processor) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{3}
}

func (x *Processor) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Processor) GetCores() uint32 {
	if x != nil && x.Cores != nil {
		return *x.Cores
	}
	return 0
}

func (x *Processor) GetThreads() uint32 {
	if x != nil && x.Threads != nil {
		return *x.Threads
	}
	return 0
}

func (x *Processor) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

func (x *Processor) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *Processor) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Memory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         *string                `protobuf:"bytes,1,opt,name=total" json:"total,omitempty"`
	Usable        *string                `protobuf:"bytes,2,opt,name=usable" json:"usable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_get_action_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{4}
}

func (x *Memory) GetTotal() string {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return ""
}

func (x *Memory) GetUsable() string {
	if x != nil && x.Usable != nil {
		return *x.Usable
	}
	return ""
}

type Block struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ControllerType    *string                `protobuf:"bytes,2,opt,name=controller_type,json=controllerType" json:"controller_type,omitempty"`
	DriveType         *string                `protobuf:"bytes,3,opt,name=drive_type,json=driveType" json:"drive_type,omitempty"`
	Size              *string                `protobuf:"bytes,4,opt,name=size" json:"size,omitempty"`
	PhysicalBlockSize *string                `protobuf:"bytes,5,opt,name=physical_block_size,json=physicalBlockSize" json:"physical_block_size,omitempty"`
	Vendor            *string                `protobuf:"bytes,6,opt,name=vendor" json:"vendor,omitempty"`
	Model             *string                `protobuf:"bytes,7,opt,name=model" json:"model,omitempty"`
	Wwn               *string                `protobuf:"bytes,8,opt,name=wwn" json:"wwn,omitempty"`
	SerialNumber      *string                `protobuf:"bytes,9,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_get_action_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{5}
}

func (x *Block) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Block) GetControllerType() string {
	if x != nil && x.ControllerType != nil {
		return *x.ControllerType
	}
	return ""
}

func (x *Block) GetDriveType() string {
	if x != nil && x.DriveType != nil {
		return *x.DriveType
	}
	return ""
}

func (x *Block) GetSize() string {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return ""
}

func (x *Block) GetPhysicalBlockSize() string {
	if x != nil && x.PhysicalBlockSize != nil {
		return *x.PhysicalBlockSize
	}
	return ""
}

func (x *Block) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

func (x *Block) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *Block) GetWwn() string {
	if x != nil && x.Wwn != nil {
		return *x.Wwn
	}
	return ""
}

func (x *Block) GetSerialNumber() string {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return ""
}

type Network struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Mac                 *string                `protobuf:"bytes,2,opt,name=mac" json:"mac,omitempty"`
	Speed               *string                `protobuf:"bytes,3,opt,name=speed" json:"speed,omitempty"`
	EnabledCapabilities []string               `protobuf:"bytes,4,rep,name=enabled_capabilities,json=enabledCapabilities" json:"enabled_capabilities,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_get_action_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{6}
}

func (x *Network) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Network) GetMac() string {
	if x != nil && x.Mac != nil {
		return *x.Mac
	}
	return ""
}

func (x *Network) GetSpeed() string {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return ""
}

func (x *Network) GetEnabledCapabilities() []string {
	if x != nil {
		return x.EnabledCapabilities
	}
	return nil
}

type PCI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        *string                `protobuf:"bytes,1,opt,name=vendor" json:"vendor,omitempty"`
	Product       *string                `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
	Class         *string                `protobuf:"bytes,3,opt,name=class" json:"class,omitempty"`
	Driver        *string                `protobuf:"bytes,4,opt,name=driver" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCI) Reset() {
	*x = PCI{}
	mi := &file_get_action_request_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCI) ProtoMessage() {}

func (x *PCI) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCI.ProtoReflect.Descriptor instead.
func (*PCI) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{7}
}

func (x *PCI) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

func (x *PCI) GetProduct() string {
	if x != nil && x.Product != nil {
		return *x.Product
	}
	return ""
}

func (x *PCI) GetClass() string {
	if x != nil && x.Class != nil {
		return *x.Class
	}
	return ""
}

func (x *PCI) GetDriver() string {
	if x != nil && x.Driver != nil {
		return *x.Driver
	}
	return ""
}

type GPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        *string                `protobuf:"bytes,1,opt,name=vendor" json:"vendor,omitempty"`
	Product       *string                `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
	Class         *string                `protobuf:"bytes,3,opt,name=class" json:"class,omitempty"`
	Driver        *string                `protobuf:"bytes,4,opt,name=driver" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPU) Reset() {
	*x = GPU{}
	mi := &file_get_action_request_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU) ProtoMessage() {}

func (x *GPU) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU.ProtoReflect.Descriptor instead.
func (*GPU) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{8}
}

func (x *GPU) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

func (x *GPU) GetProduct() string {
	if x != nil && x.Product != nil {
		return *x.Product
	}
	return ""
}

func (x *GPU) GetClass() string {
	if x != nil && x.Class != nil {
		return *x.Class
	}
	return ""
}

func (x *GPU) GetDriver() string {
	if x != nil && x.Driver != nil {
		return *x.Driver
	}
	return ""
}

type Chassis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        *string                `protobuf:"bytes,1,opt,name=serial" json:"serial,omitempty"`
	Vendor        *string                `protobuf:"bytes,2,opt,name=vendor" json:"vendor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chassis) Reset() {
	*x = Chassis{}
	mi := &file_get_action_request_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chassis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chassis) ProtoMessage() {}

func (x *Chassis) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chassis.ProtoReflect.Descriptor instead.
func (*Chassis) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{9}
}

func (x *Chassis) GetSerial() string {
	if x != nil && x.Serial != nil {
		return *x.Serial
	}
	return ""
}

func (x *Chassis) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

type BIOS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        *string                `protobuf:"bytes,1,opt,name=vendor" json:"vendor,omitempty"`
	Version       *string                `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	ReleaseDate   *string                `protobuf:"bytes,3,opt,name=release_date,json=releaseDate" json:"release_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BIOS) Reset() {
	*x = BIOS{}
	mi := &file_get_action_request_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BIOS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BIOS) ProtoMessage() {}

func (x *BIOS) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BIOS.ProtoReflect.Descriptor instead.
func (*BIOS) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{10}
}

func (x *BIOS) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

func (x *BIOS) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *BIOS) GetReleaseDate() string {
	if x != nil && x.ReleaseDate != nil {
		return *x.ReleaseDate
	}
	return ""
}

type Baseboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        *string                `protobuf:"bytes,1,opt,name=vendor" json:"vendor,omitempty"`
	Product       *string                `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
	Version       *string                `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	SerialNumber  *string                `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Baseboard) Reset() {
	*x = Baseboard{}
	mi := &file_get_action_request_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Baseboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Baseboard) ProtoMessage() {}

func (x *Baseboard) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Baseboard.ProtoReflect.Descriptor instead.
func (*Baseboard) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{11}
}

func (x *Baseboard) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

func (x *Baseboard) GetProduct() string {
	if x != nil && x.Product != nil {
		return *x.Product
	}
	return ""
}

func (x *Baseboard) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Baseboard) GetSerialNumber() string {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return ""
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Vendor        *string                `protobuf:"bytes,2,opt,name=vendor" json:"vendor,omitempty"`
	SerialNumber  *string                `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_get_action_request_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_request_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_get_action_request_proto_rawDescGZIP(), []int{12}
}

func (x *Product) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Product) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

func (x *Product) GetSerialNumber() string {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return ""
}

var File_get_action_request_proto protoreflect.FileDescriptor

const file_get_action_request_proto_rawDesc = "" +
	"\n" +
	"\x18get_action_request.proto\x12\x05proto\"m\n" +
	"\rActionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12A\n" +
	"\x10agent_attributes\x18\x02 \x01(\v2\x16.proto.AgentAttributesR\x0fagentAttributes\"\x85\x03\n" +
	"\x0fAgentAttributes\x12\x1c\n" +
	"\x03cpu\x18\x01 \x01(\v2\n" +
	".proto.CPUR\x03cpu\x12%\n" +
	"\x06memory\x18\x02 \x01(\v2\r.proto.MemoryR\x06memory\x12\"\n" +
	"\x05block\x18\x03 \x03(\v2\f.proto.BlockR\x05block\x12(\n" +
	"\anetwork\x18\x04 \x03(\v2\x0e.proto.NetworkR\anetwork\x12\x1c\n" +
	"\x03pci\x18\x05 \x03(\v2\n" +
	".proto.PCIR\x03pci\x12\x1c\n" +
	"\x03gpu\x18\x06 \x03(\v2\n" +
	".proto.GPUR\x03gpu\x12(\n" +
	"\achassis\x18\a \x01(\v2\x0e.proto.ChassisR\achassis\x12\x1f\n" +
	"\x04bios\x18\b \x01(\v2\v.proto.BIOSR\x04bios\x12.\n" +
	"\tbaseboard\x18\t \x01(\v2\x10.proto.BaseboardR\tbaseboard\x12(\n" +
	"\aproduct\x18\n" +
	" \x01(\v2\x0e.proto.ProductR\aproduct\"}\n" +
	"\x03CPU\x12\x1f\n" +
	"\vtotal_cores\x18\x01 \x01(\rR\n" +
	"totalCores\x12#\n" +
	"\rtotal_threads\x18\x02 \x01(\rR\ftotalThreads\x120\n" +
	"\n" +
	"processors\x18\x03 \x03(\v2\x10.proto.ProcessorR\n" +
	"processors\"\x9d\x01\n" +
	"\tProcessor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\rR\x05cores\x12\x18\n" +
	"\athreads\x18\x03 \x01(\rR\athreads\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\"6\n" +
	"\x06Memory\x12\x14\n" +
	"\x05total\x18\x01 \x01(\tR\x05total\x12\x16\n" +
	"\x06usable\x18\x02 \x01(\tR\x06usable\"\x8c\x02\n" +
	"\x05Block\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fcontroller_type\x18\x02 \x01(\tR\x0econtrollerType\x12\x1d\n" +
	"\n" +
	"drive_type\x18\x03 \x01(\tR\tdriveType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\x12.\n" +
	"\x13physical_block_size\x18\x05 \x01(\tR\x11physicalBlockSize\x12\x16\n" +
	"\x06vendor\x18\x06 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x10\n" +
	"\x03wwn\x18\b \x01(\tR\x03wwn\x12#\n" +
	"\rserial_number\x18\t \x01(\tR\fserialNumber\"x\n" +
	"\aNetwork\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\tR\x05speed\x121\n" +
	"\x14enabled_capabilities\x18\x04 \x03(\tR\x13enabledCapabilities\"e\n" +
	"\x03PCI\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x16\n" +
	"\x06driver\x18\x04 \x01(\tR\x06driver\"e\n" +
	"\x03GPU\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x16\n" +
	"\x06driver\x18\x04 \x01(\tR\x06driver\"9\n" +
	"\aChassis\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\"[\n" +
	"\x04BIOS\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\frelease_date\x18\x03 \x01(\tR\vreleaseDate\"|\n" +
	"\tBaseboard\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12#\n" +
	"\rserial_number\x18\x04 \x01(\tR\fserialNumber\"Z\n" +
	"\aProduct\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12#\n" +
	"\rserial_number\x18\x03 \x01(\tR\fserialNumberB\x82\x01\n" +
	"\tcom.protoB\x15GetActionRequestProtoP\x01Z*github.com/tinkerbell/tinkerbell/pkg/proto\xa2\x02\x03PXX\xaa\x02\x05Proto\xca\x02\x05Proto\xe2\x02\x11Proto\\GPBMetadata\xea\x02\x05Protob\beditionsp\xe8\a"

var (
	file_get_action_request_proto_rawDescOnce sync.Once
	file_get_action_request_proto_rawDescData []byte
)

func file_get_action_request_proto_rawDescGZIP() []byte {
	file_get_action_request_proto_rawDescOnce.Do(func() {
		file_get_action_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_action_request_proto_rawDesc), len(file_get_action_request_proto_rawDesc)))
	})
	return file_get_action_request_proto_rawDescData
}

var file_get_action_request_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_get_action_request_proto_goTypes = []any{
	(*ActionRequest)(nil),   // 0: proto.ActionRequest
	(*AgentAttributes)(nil), // 1: proto.AgentAttributes
	(*CPU)(nil),             // 2: proto.CPU
	(*Processor)(nil),       // 3: proto.Processor
	(*Memory)(nil),          // 4: proto.Memory
	(*Block)(nil),           // 5: proto.Block
	(*Network)(nil),         // 6: proto.Network
	(*PCI)(nil),             // 7: proto.PCI
	(*GPU)(nil),             // 8: proto.GPU
	(*Chassis)(nil),         // 9: proto.Chassis
	(*BIOS)(nil),            // 10: proto.BIOS
	(*Baseboard)(nil),       // 11: proto.Baseboard
	(*Product)(nil),         // 12: proto.Product
}
var file_get_action_request_proto_depIdxs = []int32{
	1,  // 0: proto.ActionRequest.agent_attributes:type_name -> proto.AgentAttributes
	2,  // 1: proto.AgentAttributes.cpu:type_name -> proto.CPU
	4,  // 2: proto.AgentAttributes.memory:type_name -> proto.Memory
	5,  // 3: proto.AgentAttributes.block:type_name -> proto.Block
	6,  // 4: proto.AgentAttributes.network:type_name -> proto.Network
	7,  // 5: proto.AgentAttributes.pci:type_name -> proto.PCI
	8,  // 6: proto.AgentAttributes.gpu:type_name -> proto.GPU
	9,  // 7: proto.AgentAttributes.chassis:type_name -> proto.Chassis
	10, // 8: proto.AgentAttributes.bios:type_name -> proto.BIOS
	11, // 9: proto.AgentAttributes.baseboard:type_name -> proto.Baseboard
	12, // 10: proto.AgentAttributes.product:type_name -> proto.Product
	3,  // 11: proto.CPU.processors:type_name -> proto.Processor
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_get_action_request_proto_init() }
func file_get_action_request_proto_init() {
	if File_get_action_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_action_request_proto_rawDesc), len(file_get_action_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_action_request_proto_goTypes,
		DependencyIndexes: file_get_action_request_proto_depIdxs,
		MessageInfos:      file_get_action_request_proto_msgTypes,
	}.Build()
	File_get_action_request_proto = out.File
	file_get_action_request_proto_goTypes = nil
	file_get_action_request_proto_depIdxs = nil
}
