// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: get_action_response.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreconditionFailureViolation int32

const (
	PreconditionFailureViolation_PRECONDITION_FAILURE_VIOLATION_UNSPECIFIED         PreconditionFailureViolation = 0
	PreconditionFailureViolation_PRECONDITION_FAILURE_VIOLATION_NO_ACTION_AVAILABLE PreconditionFailureViolation = 1
)

// Enum value maps for PreconditionFailureViolation.
var (
	PreconditionFailureViolation_name = map[int32]string{
		0: "PRECONDITION_FAILURE_VIOLATION_UNSPECIFIED",
		1: "PRECONDITION_FAILURE_VIOLATION_NO_ACTION_AVAILABLE",
	}
	PreconditionFailureViolation_value = map[string]int32{
		"PRECONDITION_FAILURE_VIOLATION_UNSPECIFIED":         0,
		"PRECONDITION_FAILURE_VIOLATION_NO_ACTION_AVAILABLE": 1,
	}
)

func (x PreconditionFailureViolation) Enum() *PreconditionFailureViolation {
	p := new(PreconditionFailureViolation)
	*p = x
	return p
}

func (x PreconditionFailureViolation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreconditionFailureViolation) Descriptor() protoreflect.EnumDescriptor {
	return file_get_action_response_proto_enumTypes[0].Descriptor()
}

func (PreconditionFailureViolation) Type() protoreflect.EnumType {
	return &file_get_action_response_proto_enumTypes[0]
}

func (x PreconditionFailureViolation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreconditionFailureViolation.Descriptor instead.
func (PreconditionFailureViolation) EnumDescriptor() ([]byte, []int) {
	return file_get_action_response_proto_rawDescGZIP(), []int{0}
}

// ActionResponse
type ActionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workflow id
	WorkflowId *string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId" json:"workflow_id,omitempty"`
	// The name of the task to which the action belongs
	TaskId *string `protobuf:"bytes,2,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	// agent_id is the id of the worker that is executing the action
	AgentId *string `protobuf:"bytes,3,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	// Action id
	ActionId *string `protobuf:"bytes,4,opt,name=action_id,json=actionId" json:"action_id,omitempty"`
	// The name of the action
	Name *string `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	// The docker/oci image the action starts from
	Image *string `protobuf:"bytes,6,opt,name=image" json:"image,omitempty"`
	// Every action has a timeout, after that the execution stops and the action
	// gets in a timeout state.
	Timeout *int64 `protobuf:"varint,7,opt,name=timeout" json:"timeout,omitempty"`
	// You can override the command executed for the container
	Command []string `protobuf:"bytes,8,rep,name=command" json:"command,omitempty"`
	// You can mount directory from your host to the running action, mainly to
	// share files, or state
	Volumes []string `protobuf:"bytes,9,rep,name=volumes" json:"volumes,omitempty"`
	// Set environment variables usable from the action itself.
	Environment []string `protobuf:"bytes,10,rep,name=environment" json:"environment,omitempty"`
	// Set the namespace that the process IDs will be in.
	Pid           *string `protobuf:"bytes,11,opt,name=pid" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_get_action_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_action_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_get_action_response_proto_rawDescGZIP(), []int{0}
}

func (x *ActionResponse) GetWorkflowId() string {
	if x != nil && x.WorkflowId != nil {
		return *x.WorkflowId
	}
	return ""
}

func (x *ActionResponse) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *ActionResponse) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

func (x *ActionResponse) GetActionId() string {
	if x != nil && x.ActionId != nil {
		return *x.ActionId
	}
	return ""
}

func (x *ActionResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ActionResponse) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *ActionResponse) GetTimeout() int64 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

func (x *ActionResponse) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ActionResponse) GetVolumes() []string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *ActionResponse) GetEnvironment() []string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ActionResponse) GetPid() string {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return ""
}

var File_get_action_response_proto protoreflect.FileDescriptor

const file_get_action_response_proto_rawDesc = "" +
	"\n" +
	"\x19get_action_response.proto\x12\x05proto\"\xae\x02\n" +
	"\x0eActionResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1b\n" +
	"\taction_id\x18\x04 \x01(\tR\bactionId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x18\n" +
	"\atimeout\x18\a \x01(\x03R\atimeout\x12\x18\n" +
	"\acommand\x18\b \x03(\tR\acommand\x12\x18\n" +
	"\avolumes\x18\t \x03(\tR\avolumes\x12 \n" +
	"\venvironment\x18\n" +
	" \x03(\tR\venvironment\x12\x10\n" +
	"\x03pid\x18\v \x01(\tR\x03pid*\x86\x01\n" +
	"\x1cPreconditionFailureViolation\x12.\n" +
	"*PRECONDITION_FAILURE_VIOLATION_UNSPECIFIED\x10\x00\x126\n" +
	"2PRECONDITION_FAILURE_VIOLATION_NO_ACTION_AVAILABLE\x10\x01B\x83\x01\n" +
	"\tcom.protoB\x16GetActionResponseProtoP\x01Z*github.com/tinkerbell/tinkerbell/pkg/proto\xa2\x02\x03PXX\xaa\x02\x05Proto\xca\x02\x05Proto\xe2\x02\x11Proto\\GPBMetadata\xea\x02\x05Protob\beditionsp\xe8\a"

var (
	file_get_action_response_proto_rawDescOnce sync.Once
	file_get_action_response_proto_rawDescData []byte
)

func file_get_action_response_proto_rawDescGZIP() []byte {
	file_get_action_response_proto_rawDescOnce.Do(func() {
		file_get_action_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_action_response_proto_rawDesc), len(file_get_action_response_proto_rawDesc)))
	})
	return file_get_action_response_proto_rawDescData
}

var file_get_action_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_get_action_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_get_action_response_proto_goTypes = []any{
	(PreconditionFailureViolation)(0), // 0: proto.PreconditionFailureViolation
	(*ActionResponse)(nil),            // 1: proto.ActionResponse
}
var file_get_action_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_get_action_response_proto_init() }
func file_get_action_response_proto_init() {
	if File_get_action_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_action_response_proto_rawDesc), len(file_get_action_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_action_response_proto_goTypes,
		DependencyIndexes: file_get_action_response_proto_depIdxs,
		EnumInfos:         file_get_action_response_proto_enumTypes,
		MessageInfos:      file_get_action_response_proto_msgTypes,
	}.Build()
	File_get_action_response_proto = out.File
	file_get_action_response_proto_goTypes = nil
	file_get_action_response_proto_depIdxs = nil
}
