// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: report_action_status_response.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionStatusResponse) Reset() {
	*x = ActionStatusResponse{}
	mi := &file_report_action_status_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStatusResponse) ProtoMessage() {}

func (x *ActionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_action_status_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStatusResponse.ProtoReflect.Descriptor instead.
func (*ActionStatusResponse) Descriptor() ([]byte, []int) {
	return file_report_action_status_response_proto_rawDescGZIP(), []int{0}
}

var File_report_action_status_response_proto protoreflect.FileDescriptor

const file_report_action_status_response_proto_rawDesc = "" +
	"\n" +
	"#report_action_status_response.proto\x12\x05proto\"\x16\n" +
	"\x14ActionStatusResponseB\x8c\x01\n" +
	"\tcom.protoB\x1fReportActionStatusResponseProtoP\x01Z*github.com/tinkerbell/tinkerbell/pkg/proto\xa2\x02\x03PXX\xaa\x02\x05Proto\xca\x02\x05Proto\xe2\x02\x11Proto\\GPBMetadata\xea\x02\x05Protob\beditionsp\xe8\a"

var (
	file_report_action_status_response_proto_rawDescOnce sync.Once
	file_report_action_status_response_proto_rawDescData []byte
)

func file_report_action_status_response_proto_rawDescGZIP() []byte {
	file_report_action_status_response_proto_rawDescOnce.Do(func() {
		file_report_action_status_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_action_status_response_proto_rawDesc), len(file_report_action_status_response_proto_rawDesc)))
	})
	return file_report_action_status_response_proto_rawDescData
}

var file_report_action_status_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_report_action_status_response_proto_goTypes = []any{
	(*ActionStatusResponse)(nil), // 0: proto.ActionStatusResponse
}
var file_report_action_status_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_report_action_status_response_proto_init() }
func file_report_action_status_response_proto_init() {
	if File_report_action_status_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_action_status_response_proto_rawDesc), len(file_report_action_status_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_report_action_status_response_proto_goTypes,
		DependencyIndexes: file_report_action_status_response_proto_depIdxs,
		MessageInfos:      file_report_action_status_response_proto_msgTypes,
	}.Build()
	File_report_action_status_response_proto = out.File
	file_report_action_status_response_proto_goTypes = nil
	file_report_action_status_response_proto_depIdxs = nil
}
