// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: workflow_service.proto

package proto

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_workflow_service_proto protoreflect.FileDescriptor

const file_workflow_service_proto_rawDesc = "" +
	"\n" +
	"\x16workflow_service.proto\x12\x05proto\x1a\x18get_action_request.proto\x1a\x19get_action_response.proto\x1a\"report_action_status_request.proto\x1a#report_action_status_response.proto2\x9e\x01\n" +
	"\x0fWorkflowService\x12:\n" +
	"\tGetAction\x12\x14.proto.ActionRequest\x1a\x15.proto.ActionResponse\"\x00\x12O\n" +
	"\x12ReportActionStatus\x12\x1a.proto.ActionStatusRequest\x1a\x1b.proto.ActionStatusResponse\"\x00B\x81\x01\n" +
	"\tcom.protoB\x14WorkflowServiceProtoP\x01Z*github.com/tinkerbell/tinkerbell/pkg/proto\xa2\x02\x03PXX\xaa\x02\x05Proto\xca\x02\x05Proto\xe2\x02\x11Proto\\GPBMetadata\xea\x02\x05Protob\beditionsp\xe8\a"

var file_workflow_service_proto_goTypes = []any{
	(*ActionRequest)(nil),        // 0: proto.ActionRequest
	(*ActionStatusRequest)(nil),  // 1: proto.ActionStatusRequest
	(*ActionResponse)(nil),       // 2: proto.ActionResponse
	(*ActionStatusResponse)(nil), // 3: proto.ActionStatusResponse
}
var file_workflow_service_proto_depIdxs = []int32{
	0, // 0: proto.WorkflowService.GetAction:input_type -> proto.ActionRequest
	1, // 1: proto.WorkflowService.ReportActionStatus:input_type -> proto.ActionStatusRequest
	2, // 2: proto.WorkflowService.GetAction:output_type -> proto.ActionResponse
	3, // 3: proto.WorkflowService.ReportActionStatus:output_type -> proto.ActionStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workflow_service_proto_init() }
func file_workflow_service_proto_init() {
	if File_workflow_service_proto != nil {
		return
	}
	file_get_action_request_proto_init()
	file_get_action_response_proto_init()
	file_report_action_status_request_proto_init()
	file_report_action_status_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_service_proto_rawDesc), len(file_workflow_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_service_proto_goTypes,
		DependencyIndexes: file_workflow_service_proto_depIdxs,
	}.Build()
	File_workflow_service_proto = out.File
	file_workflow_service_proto_goTypes = nil
	file_workflow_service_proto_depIdxs = nil
}
